routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
// Route::get('/backend', function () {

//     return view('layouts.backendmaster');

// })->middleware('auth');

Auth::routes();

// FRONT END ROUTE

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', 'FrontController@index')->name('front.index');
Route::get('/index/{lang?}', 'FrontController@index')->name('front.index');
Route::get('/about', 'FrontController@aboutus')->name('front.about');
Route::get('/yojanakaryakram', 'FrontController@yojanakaryakram')->name('front.yojanakaryakram');
Route::get('/media', 'FrontController@media')->name('front.media');
Route::get('/download', 'FrontController@download')->name('front.download');
Route::get('/pratibedhantype/{type?}', 'FrontController@pratibedhantype')->name('front.pratibedhantype');
Route::get('/contact', 'FrontController@contact')->name('front.contact');
Route::get('/boardkarya', 'FrontController@boardkarya')->name('front.boardkarya');
Route::get('/walefare', 'FrontController@walefare')->name('front.walefare');
Route::get('/walefaredetail/{category_id}', 'FrontController@walefaredetail')->name('front.walefaredetail');
Route::get('/rojgarprocess', 'FrontController@rojgarprocess')->name('front.rojgarprocess');
Route::get('/mobileapp', 'FrontController@mobileapp')->name('front.mobileapp');
Route::get('/tathyankabibaran', 'FrontController@tathyankabibaran')->name('front.tathyankabibaran');
Route::get('/chetanamulak', 'FrontController@chetanamulak')->name('front.chetanamulak');
Route::get('/chart', 'FrontController@chart')->name('front.chart');
Route::get('/chart2', 'FrontController@chart2')->name('front.chart2');
Route::get('/chart3', 'FrontController@chart3')->name('front.chart3');
Route::get('/photocollection/{catrgoty}', 'FrontController@photocollection')->name('front.photocollection');
Route::get('/lang/{lang}', 'FrontController@language')->name('front.language');


Route::get('geo-map',         ['as'=>'geo-map',           'uses' =>'FrontController@geomap']);
Route::get('insurance',       ['as'=>'insurance',         'uses' =>'FrontController@insurance']);
Route::get('orientation',     ['as'=>'orientation',       'uses' =>'FrontController@orientation']);
Route::get('district',         ['as'=>'district',            'uses' =>'FrontController@district']);
Route::get('datatable',         ['as'=>'datatable',            'uses' =>'FrontController@datatable']);



// FRONT END ROUTE Ends Here


// MAIL

Route::post('/send/email', 'MailController@mail')->name('send.mail');
Route::get('/write/mail', 'MailController@writemail');

// MAIL End Here+

// DEtail PAge
// Route::get('/detail/{busno}/{reservation}/{resnum}','frontController@busseat')->name('bus.busseat');
Route::get('/detail/{id}/{catrgoty}','FrontController@detailpage')->name('front.detailpage');
// DEtail PAge



Route::group(['prefix' => 'backend',  'middleware' => 'auth'], function()
{
    Route::resource('product_category','ProductCategoryController');
    Route::resource('setting','SettingController');
    Route::resource('slider','SliderController');
    Route::resource('about','AboutController');
    Route::resource('general','GeneralController');
    Route::resource('description','DescriptionController');
    Route::post('description_update','DescriptionController@updatestore')->name('description.updatestore');

    Route::resource('chart','ChartController');
    Route::post('chart_update','ChartController@updatestore')->name('chart.updatestore');
    Route::resource('manualTable','ManualTableController');
    Route::resource('tableEntry','TableEntryController');
    Route::resource('janaGunaso','JanaGunasoController');

    Route::resource('boardWork','BoardWorkController');
    Route::get('boardGathan/create','BoardWorkController@creategathan')->name('boardWork.creategathan');
    Route::get('board/index/{category}','BoardWorkController@boardindex');
    Route::resource('boardSachibalaya','BoardSachibalayaController');

    Route::post('contactstore','FrontController@contactstore')->name('frontcontact.store');
    Route::post('gunasostore','FrontController@gunasostore')->name('front.gunasostore');


    // this is extra page for blog
    Route::resource('blog','BlogController');
    Route::get('media_index/{category}','BlogController@mediaindex');

    Route::get('suchana/create','BlogController@suchana')->name('suchana.create');
    Route::get('press/create','BlogController@press')->name('press.create');
    Route::get('gallery/create','BlogController@gallery')->name('gallery.create');
    Route::get('video/create','BlogController@video')->name('video.create');
    Route::get('bill/create','BlogController@bill')->name('bill.create');
      // this is extra page for blog

    Route::resource('contact','ContactController');
    
    Route::resource('openCountry','OpenCountryController');
    Route::resource('neyog','NeyogController');
    Route::resource('bank','BankController');


    Route::resource('mobileApp','MobileAppController');
    Route::resource('banner','BannerController');
    Route::resource('simple','SimpleController');
    Route::resource('importantLink','ImportantLinkController');
    Route::resource('multimedia','MultimediaController');


    Route::get('multimediavideo/create','MultimediaController@multimediavideo')->name('multimediavideo.create');
    Route::get('multimediaaudio/create','MultimediaController@multimediaaudio')->name('multimediaaudio.create');
    Route::get('multimediaphoto/create','MultimediaController@multimediaphoto')->name('multimediaphoto.create');
    Route::get('basicnote/create','MultimediaController@basicnote')->name('basicnote.create');
    Route::get('faq/create','MultimediaController@faq')->name('faq.create');
    Route::get('institute/create','MultimediaController@institute')->name('institute.create');


    Route::get('chetanamulak/{category}','MultimediaController@chetanaindex');

    Route::resource('training','TrainingController');
    Route::resource('extra','ExtraController');
    Route::get('download/{category}','ExtraController@downloadindex');

    Route::get('ain/create','ExtraController@ain')->name('ain.create');


    Route::get('bulletin/create','ExtraController@bulletin')->name('bulletin.create');
    Route::get('prakashan/create','ExtraController@prakashan')->name('prakashan.create');
    Route::get('pratibedhan/create','ExtraController@pratibedhan')->name('pratibedhan.create');
    Route::get('report/create','ExtraController@report')->name('report.create');
    Route::get('other/create','ExtraController@other')->name('other.create');
    Route::get('nebadan/create','ExtraController@nebadan')->name('nebadan.create');

    Route::resource('yojanaKaryakram','YojanaKaryakramController');
    Route::get('yojanaandkaryakram/index/{category}','YojanaKaryakramController@yojanaindex');

    Route::get('yojana/karyakram','YojanaKaryakramController@createkaryakram')->name('yojanaKaryakram.karyakram');
    Route::resource('member','MemberController');
    Route::get('create_category/{type}','ProductCategoryController@createcategory')->name('createcategory.create');
    Route::get('category_index/{type}','ProductCategoryController@categoryindex')->name('createcategory.index');
});

Route::get('importExport', 'ExcelFileController@importExport')->name('excelindex');
Route::get('downloadExcel/{type}', 'ExcelFileController@downloadExcel');
Route::post('importExcel', 'ExcelFileController@importExcel');
// Route::get('/excel', 'ExcelFileController@index')->name('excelindex');
Route::post('import', 'ExcelFileController@import')->name('import');

// <a href="{{route('bus.busseat',[$singleRow->bus_no,$departDate,$resnum])}}" data-toggle="tooltip" title="Select Seat"><button>Select Seat</button></a></td>
//  <a href="{{url('/front/busseat/'.$singleRow->bus_no.'/'.$departDate.'/'.$resnum)}}" data-toggle="tooltip" title="Select Seat"><button>Select Seat</button></a></td>  --}}

app/BoardSachibalaya.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class BoardSachibalaya extends Model
{
    protected $table='board_sachibalayas';
    protected $fillable=[
        'title',
        'post',
        'resource',
        'status',
        'description',
        'created_by',
        'updated_by'
    ];
}

app/Http/Controllers/BoardSachibalayaController.php
<?php

namespace App\Http\Controllers;

use App\BoardSachibalaya;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class BoardSachibalayaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $boardSachibalaya=BoardSachibalaya::orderBy('id','desc')->get();
        // $boardSachibalaya=boardSachibalaya::where('category','boardSachibalaya')->get();
        return view('backend.boardSachibalaya.index',compact('boardSachibalaya'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $boardSachibalaya = new BoardSachibalaya();
        return view('backend.boardSachibalaya.create',compact('boardSachibalaya'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input=$request->all();

        $status=BoardSachibalaya::create($input);

        if($status){
            Session::flash('success','Information added successfully.');
        }else{
            Session::flash('error','Information cannot be added.');
        }

        return redirect('backend/boardSachibalaya');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\BoardSachibalaya  $boardSachibalaya
     * @return \Illuminate\Http\Response
     */
    public function show(BoardSachibalaya $boardSachibalaya)
    {
        return view('backend.boardSachibalaya.show',compact('boardSachibalaya'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\BoardSachibalaya  $boardSachibalaya
     * @return \Illuminate\Http\Response
     */
    public function edit(BoardSachibalaya $boardSachibalaya)
    {
        return view('backend.boardSachibalaya.create',compact('boardSachibalaya'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\BoardSachibalaya  $boardSachibalaya
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, BoardSachibalaya $boardSachibalaya)
    {
        $input = $request->all();

        $status=$boardSachibalaya->update($input);
        if($status){
            Session::flash('success','Information Updated successfully.');
        }else{
            Session::flash('error','Information Cannot be Update');
        }
        return redirect('backend/boardSachibalaya');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\BoardSachibalaya  $boardSachibalaya
     * @return \Illuminate\Http\Response
     */
    public function destroy(BoardSachibalaya $boardSachibalaya)
    {
        $status=$boardSachibalaya->delete();
        if($status){
            Session::flash('success','Information deleted successfully.');
        }else{
            Session::flash('error','Information cannot be deleted.');
        }
        return redirect('backend/boardSachibalaya');
    }
}

resources/views/backend/boardSachibalaya/create.blade.php
@extends('layouts.backmaster')



@section('content')
    <div class="container">
        <div class="row">
                <div class="col-md-8 col-lg-8 col-xl-8 col-sm-8 col-xs-8 col-lg-offset-2 col-md-offset-2 col-xs-offset-2 col-sm-offset-2 col-xl-offset-2">
                        <div class="panel panel-default">
                    <div class="panel-heading">
                        <label>Create बोर्डको सचिवालय </label>
                        <a href="{{route('boardSachibalaya.index')}}" class="btn btn-primary pull-right">बोर्डको सचिवालय List</a>
                    </div>

                    <div class="panel-body">
                            @if(!isset($boardSachibalaya->id))
                            <form method="post" action="{{route('boardSachibalaya.store')}}"  enctype="multipart/form-data" id="valid_form">
                                <input type ="hidden" class="form-control" name ="created_by" value="{{Auth::user()->id}}">

                                @else
                                <form method="post" action="{{route('boardSachibalaya.update',$boardSachibalaya)}}" method="post" enctype="multipart/form-data" id="valid_form">
                                        <input type="hidden" name="_method" value="put">

                                        <input type ="hidden" class="form-control" name ="updated_by" value="{{Auth::user()->id}}">
                                        <input type ="hidden" class="form-control" name ="created_by" value="{{$boardSachibalaya->created_by}}">
                             @endif
                            {{csrf_field()}}
                            <div class="form-group">
                                <label for="title">Title</label>
                                <input type ="text" class="form-control" name ="title" id="title" value="{{$boardSachibalaya->title}}" >
                                @if ($errors->has('title'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif

                            </div>
                            <div class="form-group">
                                <label for="post">post</label>
                                <input type ="text" class="form-control" name ="post" id="post" value="{{$boardSachibalaya->post}}" >
                                @if ($errors->has('post'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('post') }}</strong>
                                    </span>
                                @endif

                            </div>
                            <div class="form-group">
                                <label for="resource">resource</label>
                                <input type ="text" class="form-control" name ="resource" id="resource" value="{{$boardSachibalaya->resource}}" >
                                @if ($errors->has('resource'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('resource') }}</strong>
                                    </span>
                                @endif

                            </div>

                            <div class="form-group">
                                <label>Status</label>
                                <input type ="radio"  name ="status" checked value="1">Active
                                <input type ="radio"  name ="status" value="0" > Deactive
                            </div>
                            <div class="form-group">
                                <label for="description">Description</label>
                                <textarea class="form-control" name ="description" id="description"  required>{!!$boardSachibalaya->description!!} </textarea>
                                @if ($errors->has('description'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif

                            </div>



                            <div class="form-group">
                                <input class="btn btn-success" type ="submit" name ="submit" value="Save Information">

                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/boardSachibalaya/edit.blade.php
@extends('adminlte::page')
@section('js')
    <script type="text/javascript" src="{{asset('assets/ckeditor/ckeditor.js')}}"></script>
    {{--<script type="text/javascript" src="{{asset('assets/jqueryvalidation/dist/jquery.validate.min.js')}}"></script>--}}
    {{--<script type="text/javascript">--}}
    {{--$(document).ready(function () {--}}
    {{--$('#slider_form').validate({--}}
    {{--rules: {--}}
    {{--'description': {--}}
    {{--required: true--}}
    {{--}--}}
    {{--},--}}
    {{--messages: {--}}
    {{--title: "This field is required.",--}}
    {{--link: "This field is required.",--}}
    {{--image: "This field is required.",--}}
    {{--rank: "This field is required.",--}}
    {{--description: "This field is required."--}}
    {{--},--}}
    {{--ignore: []--}}
    {{--});--}}
    {{--});--}}
    {{--</script>--}}
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <label>Edit Slider</label>
                        <a href="{{route('slider.index')}}" class="btn btn-primary pull-right">Slider List</a>
                    </div>

                    <div class="panel-body">
                        <form method="post" action="{{route('slider.update',$slider)}}" method="post" id="slider_form">
                            <input type="hidden" name="_method" value="put">
                            {{csrf_field()}}
                            <div class="form-group">
                                <label for="title">Title</label>
                                <input type ="text" class="form-control" name ="title" value="{{$slider->title}}" id="title" required>
                                @if ($errors->has('title'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif

                            </div>


                            <div class="form-group">
                                <label for="image">Image</label>
                                <input type ="text" class="form-control" name ="image" value="{{$slider->image}}" id="image" required>
                                @if ($errors->has('image'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('image') }}</strong>
                                    </span>
                                @endif

                            </div>
                            <div class="form-group">
                                <label for="rank">Rank</label>
                                <input type ="number" class="form-control" name ="rank" value="{{$slider->rank}}" id="rank" required>
                                @if ($errors->has('rank'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('rank') }}</strong>
                                    </span>
                                @endif

                            </div>

                            <div class="form-group">
                                <label>Status</label>
                                @if($slider->status==1)

                                    <input type ="radio"  name ="status" value="1" checked>Active
                                    <input type ="radio"  name ="status" value="0" > Inactive
                                @else
                                    <input type ="radio"  name ="status" value="1" >Active
                                    <input type ="radio"  name ="status" value="0" checked>Inactive
                                @endif

                            </div>
                            <div class="form-group">
                                <label for="description">Description</label>
                                <textarea class="form-control ckeditor " name ="description" id="description" required>{{$slider->description}}</textarea>
                                @if ($errors->has('description'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif

                            </div>
                            <div class="form-group">
                                <!-- <label>Created By</label>-->
                                <input type ="hidden" class="form-control" name ="created_by" value="{{$slider->created_by}}">

                            </div>
                            <div class="form-group">
                                <!-- <label>Updated By</label>-->
                                <input type ="hidden" class="form-control" name ="updated_by" value="{{Auth::user()->id}}">

                            </div>

                            <div class="form-group">
                                <input class="btn btn-success" type ="submit" name ="submit" value="Update Slider">

                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/boardSachibalaya/index.blade.php
@extends('layouts.backmaster')
@section('css')
    {{--  <link type="text/css" rel="stylesheet" href="{{asset('assets/datatables/css/jquery.dataTables.min.css')}}">  --}}
@endsection

@section('javascript')
    {{--  <script type="text/javascript" src="{{asset('assets/datatables/js/jquery.dataTables.min.js')}}"></script>  --}}
    {{--  <script type="text/javascript">
        $(document).ready(function(){
            $('#boardSachibalaya_table').DataTable();
        });
    </script>  --}}
@endsection

@section('content')
    <div class="container">
        <div class="row">
                <div class="col-md-8 col-lg-8 col-xl-8 col-sm-8 col-xs-8 col-lg-offset-2 col-md-offset-2 col-xs-offset-2 col-sm-offset-2 col-xl-offset-2">
                        <div class="panel panel-default">
                    <div class="panel-heading">
                        <label>बोर्डको सचिवालय List</label>
                        <a href="{{route('boardSachibalaya.create')}}" class="btn btn-primary pull-right">Create बोर्डको सचिवालय</a>
                    </div>

                    <div class="panel-body">
                        @if(Session::has('success'))
                            <div class="alert alert-success">
                                {{ Session::get('success') }}
                            </div>
                        @endif
                        @if(Session::has('error'))
                            <div class="alert alert-danger">
                                {{ Session::get('error') }}
                            </div>
                        @endif

                        <table class="table table-bordered" id="data_table">
                            <thead>
                            <tr>

                                <th>SN</th>
                                <th>Title</th>
                                <th>Post</th>
                                <th>Status</th>
                                <th>Action</th>


                            </tr>
                            </thead>

                            <tbody>
                            @php($i=1)
                            @foreach($boardSachibalaya as $s)
                                <tr>

                                    <td>{{$i++}}</td>
                                    <td>{{$s->title}}</td>
                                    <td>{{$s->post}}</td>

                                    <td>
                                        @if($s->status==1)
                                            <label class="label label-success">Active</label>
                                        @else
                                            <label class="label label-danger">Inactive</label>
                                        @endif
                                    </td>
                                    <td>
                                        <a href="{{route('boardSachibalaya.edit',$s)}}" class="btn btn-warning btn-block">Edit</a>
                                        <a href="{{route('boardSachibalaya.show',$s)}}" class="btn btn-info btn-block">View Detail</a>

                                        <form action="{{route('boardSachibalaya.destroy',$s)}}" method="post" onsubmit="return confirm('Are You Sure??')">
                                            <input type="hidden" name="_method" value="delete">
                                            {{csrf_field()}}
                                            <input type="submit" value="Delete" class="btn btn-danger btn-block" >
                                        </form>
                                    </td>
                                </tr>
                            @endforeach

                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/boardSachibalaya/show.blade.php
@extends('layouts.backmaster')

@section('content')
    <div class="container">
        <div class="row">
                <div class="col-md-8 col-lg-8 col-xl-8 col-sm-8 col-xs-8 col-lg-offset-2 col-md-offset-2 col-xs-offset-2 col-sm-offset-2 col-xl-offset-2">
                        <div class="panel panel-default">
                    <div class="panel-heading">
                        <label>बोर्डको सचिवालय Detail</label>
                        <a href="{{route('boardSachibalaya.index')}}" class="btn btn-primary pull-right">बोर्डको सचिवालय List</a>
                    </div>

                    <div class="panel-body">
                        <table class="table table-bordered ">
                            <tr>
                                <th>Title</th>
                                <td>{{$boardSachibalaya->title}}</td>
                            </tr>




                            <tr>
                                <th>Status</th>
                                <td>
                                    @if($boardSachibalaya->status==1)
                                        <label class="label label-success">Active</label>
                                    @else
                                        <label class="label label-danger">Deactive</label>
                                    @endif
                                </td>
                            </tr>
                            <tr>
                                <th>Description</th>
                                <td>{!!$boardSachibalaya->description!!}</td>
                            </tr>
                            <tr>
                                <th>Post</th>
                                <td>{{$boardSachibalaya->post}}</td>
                            </tr>
                            <tr>
                                <th>Created By</th>
                                <td>{{\App\User::find($boardSachibalaya->created_by)->name}}</td>
                            </tr>
                            <tr>
                                <th>Updated By</th>
                                <td>
                                    @if(!empty($boardSachibalaya->updated_by))
                                        {{\App\User::find($boardSachibalaya->updated_by)->name}}
                                    @endif
                                </td>
                            </tr>
                            <tr>
                                <th>Created At</th>
                                <td>{{$boardSachibalaya->created_at}}</td>
                            </tr>
                            <tr>
                                <th>Updated At</th>
                                <td>{{$boardSachibalaya->updated_at}}</td>
                            </tr>

                            <tr>
                                <td>
                                    <a href="{{route('boardSachibalaya.edit',$boardSachibalaya)}}" class="btn btn-warning">Edit boardSachibalaya</a>
                                </td>
                                <td>
                                    <form action="{{route('boardSachibalaya.destroy',$boardSachibalaya)}}" method="post" onsubmit="return confirm('Are You Sure??')">
                                        <input type="hidden" name="_method" value="delete">
                                        {{csrf_field()}}
                                        <input type="submit" value="Delete" class="btn btn-danger">
                                    </form>

                                </td>
                            </tr>
                        </table>


                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection