routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
// Route::get('/backend', function () {

//     return view('layouts.backendmaster');

// })->middleware('auth');

Auth::routes();

// FRONT END ROUTE

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', 'FrontController@index')->name('front.index');
Route::get('/index/{lang?}', 'FrontController@index')->name('front.index');
Route::get('/about', 'FrontController@aboutus')->name('front.about');
Route::get('/yojanakaryakram', 'FrontController@yojanakaryakram')->name('front.yojanakaryakram');
Route::get('/media', 'FrontController@media')->name('front.media');
Route::get('/download', 'FrontController@download')->name('front.download');
Route::get('/pratibedhantype/{type?}', 'FrontController@pratibedhantype')->name('front.pratibedhantype');
Route::get('/contact', 'FrontController@contact')->name('front.contact');
Route::get('/boardkarya', 'FrontController@boardkarya')->name('front.boardkarya');
Route::get('/walefare', 'FrontController@walefare')->name('front.walefare');
Route::get('/walefaredetail/{category_id}', 'FrontController@walefaredetail')->name('front.walefaredetail');
Route::get('/rojgarprocess', 'FrontController@rojgarprocess')->name('front.rojgarprocess');
Route::get('/mobileapp', 'FrontController@mobileapp')->name('front.mobileapp');
Route::get('/tathyankabibaran', 'FrontController@tathyankabibaran')->name('front.tathyankabibaran');
Route::get('/chetanamulak', 'FrontController@chetanamulak')->name('front.chetanamulak');
Route::get('/chart', 'FrontController@chart')->name('front.chart');
Route::get('/chart2', 'FrontController@chart2')->name('front.chart2');
Route::get('/chart3', 'FrontController@chart3')->name('front.chart3');
Route::get('/photocollection/{catrgoty}', 'FrontController@photocollection')->name('front.photocollection');
Route::get('/lang/{lang}', 'FrontController@language')->name('front.language');


Route::get('geo-map',         ['as'=>'geo-map',           'uses' =>'FrontController@geomap']);
Route::get('insurance',       ['as'=>'insurance',         'uses' =>'FrontController@insurance']);
Route::get('orientation',     ['as'=>'orientation',       'uses' =>'FrontController@orientation']);
Route::get('district',         ['as'=>'district',            'uses' =>'FrontController@district']);
Route::get('datatable',         ['as'=>'datatable',            'uses' =>'FrontController@datatable']);



// FRONT END ROUTE Ends Here


// MAIL

Route::post('/send/email', 'MailController@mail')->name('send.mail');
Route::get('/write/mail', 'MailController@writemail');

// MAIL End Here+

// DEtail PAge
// Route::get('/detail/{busno}/{reservation}/{resnum}','frontController@busseat')->name('bus.busseat');
Route::get('/detail/{id}/{catrgoty}','FrontController@detailpage')->name('front.detailpage');
// DEtail PAge



Route::group(['prefix' => 'backend',  'middleware' => 'auth'], function()
{
    Route::resource('product_category','ProductCategoryController');
    Route::resource('setting','SettingController');
    Route::resource('slider','SliderController');
    Route::resource('about','AboutController');
    Route::resource('general','GeneralController');
    Route::resource('description','DescriptionController');
    Route::post('description_update','DescriptionController@updatestore')->name('description.updatestore');

    Route::resource('chart','ChartController');
    Route::post('chart_update','ChartController@updatestore')->name('chart.updatestore');
    Route::resource('manualTable','ManualTableController');
    Route::resource('tableEntry','TableEntryController');
    Route::resource('janaGunaso','JanaGunasoController');

    Route::resource('boardWork','BoardWorkController');
    Route::get('boardGathan/create','BoardWorkController@creategathan')->name('boardWork.creategathan');
    Route::get('board/index/{category}','BoardWorkController@boardindex');
    Route::resource('boardSachibalaya','BoardSachibalayaController');

    Route::post('contactstore','FrontController@contactstore')->name('frontcontact.store');
    Route::post('gunasostore','FrontController@gunasostore')->name('front.gunasostore');


    // this is extra page for blog
    Route::resource('blog','BlogController');
    Route::get('media_index/{category}','BlogController@mediaindex');

    Route::get('suchana/create','BlogController@suchana')->name('suchana.create');
    Route::get('press/create','BlogController@press')->name('press.create');
    Route::get('gallery/create','BlogController@gallery')->name('gallery.create');
    Route::get('video/create','BlogController@video')->name('video.create');
    Route::get('bill/create','BlogController@bill')->name('bill.create');
      // this is extra page for blog

    Route::resource('contact','ContactController');
    
    Route::resource('openCountry','OpenCountryController');
    Route::resource('neyog','NeyogController');
    Route::resource('bank','BankController');


    Route::resource('mobileApp','MobileAppController');
    Route::resource('banner','BannerController');
    Route::resource('simple','SimpleController');
    Route::resource('importantLink','ImportantLinkController');
    Route::resource('multimedia','MultimediaController');


    Route::get('multimediavideo/create','MultimediaController@multimediavideo')->name('multimediavideo.create');
    Route::get('multimediaaudio/create','MultimediaController@multimediaaudio')->name('multimediaaudio.create');
    Route::get('multimediaphoto/create','MultimediaController@multimediaphoto')->name('multimediaphoto.create');
    Route::get('basicnote/create','MultimediaController@basicnote')->name('basicnote.create');
    Route::get('faq/create','MultimediaController@faq')->name('faq.create');
    Route::get('institute/create','MultimediaController@institute')->name('institute.create');


    Route::get('chetanamulak/{category}','MultimediaController@chetanaindex');

    Route::resource('training','TrainingController');
    Route::resource('extra','ExtraController');
    Route::get('download/{category}','ExtraController@downloadindex');

    Route::get('ain/create','ExtraController@ain')->name('ain.create');


    Route::get('bulletin/create','ExtraController@bulletin')->name('bulletin.create');
    Route::get('prakashan/create','ExtraController@prakashan')->name('prakashan.create');
    Route::get('pratibedhan/create','ExtraController@pratibedhan')->name('pratibedhan.create');
    Route::get('report/create','ExtraController@report')->name('report.create');
    Route::get('other/create','ExtraController@other')->name('other.create');
    Route::get('nebadan/create','ExtraController@nebadan')->name('nebadan.create');

    Route::resource('yojanaKaryakram','YojanaKaryakramController');
    Route::get('yojanaandkaryakram/index/{category}','YojanaKaryakramController@yojanaindex');

    Route::get('yojana/karyakram','YojanaKaryakramController@createkaryakram')->name('yojanaKaryakram.karyakram');
    Route::resource('member','MemberController');
    Route::get('create_category/{type}','ProductCategoryController@createcategory')->name('createcategory.create');
    Route::get('category_index/{type}','ProductCategoryController@categoryindex')->name('createcategory.index');
});

Route::get('importExport', 'ExcelFileController@importExport')->name('excelindex');
Route::get('downloadExcel/{type}', 'ExcelFileController@downloadExcel');
Route::post('importExcel', 'ExcelFileController@importExcel');
// Route::get('/excel', 'ExcelFileController@index')->name('excelindex');
Route::post('import', 'ExcelFileController@import')->name('import');

// <a href="{{route('bus.busseat',[$singleRow->bus_no,$departDate,$resnum])}}" data-toggle="tooltip" title="Select Seat"><button>Select Seat</button></a></td>
//  <a href="{{url('/front/busseat/'.$singleRow->bus_no.'/'.$departDate.'/'.$resnum)}}" data-toggle="tooltip" title="Select Seat"><button>Select Seat</button></a></td>  --}}

app/MobileApp.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class MobileApp extends Model
{
    protected $table='mobile_apps';
    protected $fillable=[
        'title',
        'status',
        'description',
        'link',
        'image',
        'mobile_image',
        'short_description',
        'created_by',
        'updated_by'
    ];
}

app/Http/Controllers/MobileAppController.php
<?php

namespace App\Http\Controllers;

use App\MobileApp;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class MobileAppController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $mobileApp=MobileApp::all();
        return view('backend.mobileApp.index',compact('mobileApp'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $mobileApp = new MobileApp();
        return view('backend.mobileApp.create',compact('mobileApp'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input=$request->all();

        $image='';
        if(!empty($request->file('image'))){
            $file =$request->file('image');
            $path=base_path().'/public/mobileApp_upload';
            $name=uniqid().'_'.$file->getClientOriginalName();
            if($file->move($path,$name)){
                $image=$name;
                $input['image']=$image;
            }
        }
        $mobile_image='';
        if(!empty($request->file('mobile_image'))){
            $file =$request->file('mobile_image');
            $path=base_path().'/public/mobileApp_upload';
            $name=uniqid().'_'.$file->getClientOriginalName();
            if($file->move($path,$name)){
                $mobile_image=$name;
                $input['mobile_image']=$mobile_image;

            }
        }
        $status=MobileApp::create($input);

        if($status){
            Session::flash('success','Information added successfully.');
        }else{
            Session::flash('error','Information cannot be added.');
        }

        return redirect('backend/mobileApp');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\MobileApp  $mobileApp
     * @return \Illuminate\Http\Response
     */
    public function show(MobileApp $mobileApp)
    {
        return view('backend.mobileApp.show',compact('mobileApp'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\MobileApp  $mobileApp
     * @return \Illuminate\Http\Response
     */
    public function edit(MobileApp $mobileApp)
    {
        return view('backend.mobileApp.create',compact('mobileApp'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\MobileApp  $mobileApp
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, MobileApp $mobileApp)
    {
        $input = $request->all();
        // dd($request);
        $image='';
        if(!empty($request->file('image'))){
            $file =$request->file('image');
            $path=base_path().'/public/mobileApp_upload';
            $name=uniqid().'_'.$file->getClientOriginalName();
            if($file->move($path,$name)){
                $image=$name;
                $input['image']=$image;

            }
        }
        $mobile_image='';
        if(!empty($request->file('mobile_image'))){
            $file =$request->file('mobile_image');
            $path=base_path().'/public/mobileApp_upload';
            $name=uniqid().'_'.$file->getClientOriginalName();
            if($file->move($path,$name)){
                $mobile_image=$name;
                $input['mobile_image']=$mobile_image;

            }
        }
        // dd($input);

        $status=$mobileApp->update($input);
        if($status){
            Session::flash('success','Information Updated successfully.');
        }else{
            Session::flash('error','Information Cannot be Update');
        }
        return redirect('backend/mobileApp');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\MobileApp  $mobileApp
     * @return \Illuminate\Http\Response
     */
    public function destroy(MobileApp $mobileApp)
    {
        $status=$mobileApp->delete();
        if($status){
            Session::flash('success','Information deleted successfully.');
        }else{
            Session::flash('error','Information cannot be deleted.');
        }
        return redirect('backend/mobileApp');
    }
}

resources/views/backend/mobileApp/create.blade.php
@extends('layouts.backmaster')



@section('content')
    <div class="container">
        <div class="row">
                <div class="col-md-8 col-lg-8 col-xl-8 col-sm-8 col-xs-8 col-lg-offset-2 col-md-offset-2 col-xs-offset-2 col-sm-offset-2 col-xl-offset-2">
                        <div class="panel panel-default">
                    <div class="panel-heading">
                        <label>Create mobileApp</label>
                        <a href="{{route('mobileApp.index')}}" class="btn btn-primary pull-right">mobileApp List</a>
                    </div>

                    <div class="panel-body">
                            @if(!isset($mobileApp->id))
                            <form method="post" action="{{route('mobileApp.store')}}"  enctype="multipart/form-data" id="valid_form">
                                <input type ="hidden" class="form-control" name ="created_by" value="{{Auth::user()->id}}">

                                @else
                                <form method="post" action="{{route('mobileApp.update',$mobileApp)}}" method="post" enctype="multipart/form-data" id="valid_form">
                                        <input type="hidden" name="_method" value="put">

                                        <input type ="hidden" class="form-control" name ="updated_by" value="{{Auth::user()->id}}">
                                        <input type ="hidden" class="form-control" name ="created_by" value="{{$mobileApp->created_by}}">
                             @endif
                            {{csrf_field()}}
                            <div class="form-group">
                                <label for="title">Title</label>
                                <input type ="text" class="form-control" name ="title" id="title" value="{{$mobileApp->title}}" required>
                                @if ($errors->has('title'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif

                            </div>
                            <div class="form-group">
                                <label for="link">link</label>
                                <input type ="text" class="form-control" name ="link" id="link" value="{{$mobileApp->link}}" required>
                                @if ($errors->has('link'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('link') }}</strong>
                                    </span>
                                @endif

                            </div>

                            <div class="form-group">
                                <label for="image">image</label>

                                <input type="file" name="image" id="image" class="form-control" value="{{$mobileApp->image}}">

                                <td><img src="{{asset('/mobileApp_upload/'.$mobileApp->image)}}" height="100" width="100"></td>

                            </div>
                            <div class="form-group">
                                <label for="mobile_image">Mobile image</label>

                                <input type="file" name="mobile_image" id="mobile_image" class="form-control" value="{{$mobileApp->mobile_image}}">

                                <td><img src="{{asset('/mobileApp_upload/'.$mobileApp->mobile_image)}}" height="100" width="100"></td>

                            </div>



                            <div class="form-group">
                                <label>Status</label>
                                <input type ="radio"  name ="status" checked value="1">Active
                                <input type ="radio"  name ="status" value="0" > Deactive
                            </div>
                            <div class="form-group">
                                <label for="description">Description</label>
                                <textarea class="form-control ckeditor" name ="description" id="description"  required>{!!$mobileApp->description!!} </textarea>
                                @if ($errors->has('description'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif

                            </div>
                            <div class="form-group">
                                <label for="short_description">Short Description</label>
                                <textarea class="form-control ckeditor" name ="short_description" id="short_description"  required>{!!$mobileApp->short_description!!} </textarea>
                                @if ($errors->has('short_description'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('short_description') }}</strong>
                                    </span>
                                @endif

                            </div>


                            <div class="form-group">
                                <input class="btn btn-success" type ="submit" name ="submit" value="Save mobileApp">

                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/mobileApp/edit.blade.php
@extends('adminlte::page')
@section('js')
    <script type="text/javascript" src="{{asset('assets/ckeditor/ckeditor.js')}}"></script>
    {{--<script type="text/javascript" src="{{asset('assets/jqueryvalidation/dist/jquery.validate.min.js')}}"></script>--}}
    {{--<script type="text/javascript">--}}
    {{--$(document).ready(function () {--}}
    {{--$('#slider_form').validate({--}}
    {{--rules: {--}}
    {{--'description': {--}}
    {{--required: true--}}
    {{--}--}}
    {{--},--}}
    {{--messages: {--}}
    {{--title: "This field is required.",--}}
    {{--link: "This field is required.",--}}
    {{--image: "This field is required.",--}}
    {{--rank: "This field is required.",--}}
    {{--description: "This field is required."--}}
    {{--},--}}
    {{--ignore: []--}}
    {{--});--}}
    {{--});--}}
    {{--</script>--}}
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <label>Edit Slider</label>
                        <a href="{{route('slider.index')}}" class="btn btn-primary pull-right">Slider List</a>
                    </div>

                    <div class="panel-body">
                        <form method="post" action="{{route('slider.update',$slider)}}" method="post" id="slider_form">
                            <input type="hidden" name="_method" value="put">
                            {{csrf_field()}}
                            <div class="form-group">
                                <label for="title">Title</label>
                                <input type ="text" class="form-control" name ="title" value="{{$slider->title}}" id="title" required>
                                @if ($errors->has('title'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif

                            </div>


                            <div class="form-group">
                                <label for="image">Image</label>
                                <input type ="text" class="form-control" name ="image" value="{{$slider->image}}" id="image" required>
                                @if ($errors->has('image'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('image') }}</strong>
                                    </span>
                                @endif

                            </div>
                            <div class="form-group">
                                <label for="rank">Rank</label>
                                <input type ="number" class="form-control" name ="rank" value="{{$slider->rank}}" id="rank" required>
                                @if ($errors->has('rank'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('rank') }}</strong>
                                    </span>
                                @endif

                            </div>

                            <div class="form-group">
                                <label>Status</label>
                                @if($slider->status==1)

                                    <input type ="radio"  name ="status" value="1" checked>Active
                                    <input type ="radio"  name ="status" value="0" > Inactive
                                @else
                                    <input type ="radio"  name ="status" value="1" >Active
                                    <input type ="radio"  name ="status" value="0" checked>Inactive
                                @endif

                            </div>
                            <div class="form-group">
                                <label for="description">Description</label>
                                <textarea class="form-control ckeditor " name ="description" id="description" required>{{$slider->description}}</textarea>
                                @if ($errors->has('description'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif

                            </div>
                            <div class="form-group">
                                <!-- <label>Created By</label>-->
                                <input type ="hidden" class="form-control" name ="created_by" value="{{$slider->created_by}}">

                            </div>
                            <div class="form-group">
                                <!-- <label>Updated By</label>-->
                                <input type ="hidden" class="form-control" name ="updated_by" value="{{Auth::user()->id}}">

                            </div>

                            <div class="form-group">
                                <input class="btn btn-success" type ="submit" name ="submit" value="Update Slider">

                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/mobileApp/index.blade.php
@extends('layouts.backmaster')
@section('css')
    {{--  <link type="text/css" rel="stylesheet" href="{{asset('assets/datatables/css/jquery.dataTables.min.css')}}">  --}}
@endsection

@section('javascript')
    {{--  <script type="text/javascript" src="{{asset('assets/datatables/js/jquery.dataTables.min.js')}}"></script>  --}}
    {{--  <script type="text/javascript">
        $(document).ready(function(){
            $('#mobileApp_table').DataTable();
        });
    </script>  --}}
@endsection

@section('content')
    <div class="container">
        <div class="row">
                <div class="col-md-8 col-lg-8 col-xl-8 col-sm-8 col-xs-8 col-lg-offset-2 col-md-offset-2 col-xs-offset-2 col-sm-offset-2 col-xl-offset-2">
                        <div class="panel panel-default">
                    <div class="panel-heading">
                        <label>mobileApp List</label>
                        {{--  <a href="{{route('mobileApp.create')}}" class="btn btn-primary pull-right">Create mobileApp</a>  --}}
                    </div>

                    <div class="panel-body">
                        @if(Session::has('success'))
                            <div class="alert alert-success">
                                {{ Session::get('success') }}
                            </div>
                        @endif
                        @if(Session::has('error'))
                            <div class="alert alert-danger">
                                {{ Session::get('error') }}
                            </div>
                        @endif

                        <table class="table table-bordered" id="data_table">
                            <thead>
                            <tr>

                                <th>SN</th>
                                <th>Title</th>
                                <th>Status</th>
                                <th>Action</th>


                            </tr>
                            </thead>

                            <tbody>
                            @php($i=1)
                            @foreach($mobileApp as $s)
                                <tr>

                                    <td>{{$i++}}</td>
                                    <td>{{$s->title}}</td>

                                    <td>
                                        @if($s->status==1)
                                            <label class="label label-success">Active</label>
                                        @else
                                            <label class="label label-danger">Inactive</label>
                                        @endif
                                    </td>
                                    <td>
                                        <a href="{{route('mobileApp.edit',$s)}}" class="btn btn-warning btn-block">Edit</a>
                                        <a href="{{route('mobileApp.show',$s)}}" class="btn btn-info btn-block">View Detail</a>

                                        {{--  <form action="{{route('mobileApp.destroy',$s)}}" method="post" onsubmit="return confirm('Are You Sure??')">
                                            <input type="hidden" name="_method" value="delete">
                                            {{csrf_field()}}
                                            <input type="submit" value="Delete" class="btn btn-danger btn-block" >
                                        </form>  --}}
                                    </td>
                                </tr>
                            @endforeach

                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection